packages:
  - 'packages/*'
gitChecks: false
publishBranch: main
allowBuilds:
  '@biomejs/biome': true
  '@swc/core': true
  esbuild: true
  koffi: true
  nx: true
  protobufjs: true
  unrs-resolver: true

autoInstallPeers: true
strictPeerDependencies: false
